name: On Push to Main

on:
  push:  
    branches:
      - main 

jobs:
  build_and_test:
    runs-on: ubuntu-latest 
    steps:
      - name: Print message
        run: echo "This action runs on every commit to main, including merges!"
