name: Pull Request commit

on:
  pull_request:  
    branches:
      - main  

jobs:
  build_and_test:
    runs-on: ubuntu-latest 
    steps:
      - name: Print message
        run: echo "This action runs on every PR!"  # Print a message
